### PR TITLE
add-gh-issue-templates

### LINKED ISSUE #28: Add Github Issue Template with different
Different template structures for:
- enhancement
- bugs

### PR DESCRIPTION
**Pull request by harikesh409**
Fixes #28

### CODE REVIEW

**Comment by Ankit-11525** [comment]
what the effect of this please clarify!

**Comment by harikesh409** [comment]
While creating a new issue instead of starting with a blank template the content in the md files act as a helper while creating issues.

**Comment by Ankit-11525** [comment]
How i can see these changes before merging it , please share screenshot if possible.

**Comment by harikesh409** [comment]
@Ankit-11525 , Just check the code I can't provide any screenshots as it is not an HTML page. It's a markdown template the text is pretty straight forward, check and let me know if you want to change any text.

**Pull request merged**
