### PR TITLE
Changed price format and some minor typos

### PR DESCRIPTION
**Pull request by SandeshGC**
This solves issue #23 
I have changed the price format from "550 Rs." to standard format: "Rs. 550" and have fixed some minor typos in the webiste.

Before:

cart-page--before

all-products-page--before

After:

cart-page

all-products-page

### CODE REVIEW

**Review by SandeshGC — COMMENTED** [review]
(I found this only in the home page, this commit does not solve any issue)
Before:

image

After:

image

**Comment by Ankit-11525** [comment]
oh okay

**Comment by SandeshGC** [comment]
Hey @Ankit-11525 
I need some help, I first created the pull request, then later I synced my branch with your main branch, now I don't know what has happend. My changes have not been merged and the code in my branch is not functioning well.

**Comment by Ankit-11525** [comment]
I guess somebody has update it

**Comment by SandeshGC** [comment]
Ok, I'll look into it.

**Pull request closed without merging**
