### PR TITLE
solution for issue regarding addition of items to cart (#12)

### PR DESCRIPTION
**Pull request by PrajwalDhule**
Hello! I have completed the solution for the allotted issue. I have used local storage to store the added items and then listed them in the cart page and also made the total section dynamic.

### CODE REVIEW

**Comment by Ankit-11525** [comment]
please deploy it at your end and share link , so that i can see the changes , also helps in future

**Comment by PrajwalDhule** [comment]
> please deploy it at your end and share link , so that i can see the changes , also helps in future
Here:
Website: https://e-commerce-redstore-prajwal.netlify.app/
Github: https://github.com/PrajwalDhule/e-commerce_redstore.github.io

**Comment by Ankit-11525** [comment]
Amazing !! thats great

**Comment by Ankit-11525** [comment]
Is it only for first red tshirt ?

**Comment by PrajwalDhule** [comment]
> 

Yes, it is only for the first red tshirt, because, If I am not wrong, the product detail page was available only for that product. So I could only add to cart and get product info from there. 

Making the product detail page dynamic and displaying the product details (highly suggesting using a database) after clicking a product would be better. This way the item can be added to the cart based on just it's id through a database.

As for what I did, when clicking on add to cart button, I obtained the details from the product detail page's html and stored it into an object which i appended into a user item which I stored in the localstorage as it can be accessed anywhere in the website. This way i could get the product on the cart page and display every added product by looping through the cart array present in the user item.

If you want a more detailed explanation or a proper documentation, let me know. 
Have a good day!

**Comment by Ankit-11525** [comment]
yeah sure ,please!

**Comment by PrajwalDhule** [comment]
> yeah sure ,please!

Sorry for the delay, here is a google doc containing the documentation I could come up with. I hope you find it useful.
https://docs.google.com/document/d/1fDhKZbC_5PE2mg4Dvxp4WSxux9BKlfwkMuq_M3tnAuY/edit?usp=sharing

**Pull request merged**
