### PR TITLE
Modified Login and Registration card UI

### LINKED ISSUE #55: Enhance Login/Register Card
**Is your feature request related to a problem? Please describe.**
In the account details page, Login/Register card looks very basic.

**Describe the solution you'd like**
I want to enhance the Login/Register card by adding additional styling so that it will look much better.

**Screenshot**

products

### PR DESCRIPTION
**Pull request by rtewari056**
## Type of change
Added custom styling on the Login/Register Card.

### Before adding custom styles
193732069-8a53d6e4-fb2d-4ceb-8b02-d35e89594ad8

### After adding custom styles
screenshot-github

### CODE REVIEW

**Comment by Ankit-11525** [comment]
Please resolve conflicts!

**Comment by rtewari056** [comment]
> Please resolve conflicts!

@Ankit-11525 Resolved

**Comment by Ankit-11525** [comment]
but its again showing  
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/Ankit-11525/e-commerce_redstore.github.io/pull/64/conflicts) or the  to resolve conflicts.
Conflicting files
style.css

**Comment by rtewari056** [comment]
### From my side I fixed it again and now its showing no conflicts (Check the screenshot below)
PRs

**Comment by Ankit-11525** [comment]
yes!

**Pull request merged**
