### PR TITLE
Changed Price formatting

### PR DESCRIPTION
**Pull request by SandeshGC**
I have changed the price formatting and fixed some minor typos. 
Let's see if this PR causes some conflicts or not.

### CODE REVIEW

**Comment by SandeshGC** [comment]
You can find more details about this change here:
https://github.com/Ankit-11525/e-commerce_redstore.github.io/pull/56#issue-1395757166

**Comment by Ankit-11525** [comment]
@SandeshGC  Bro please help me , due to some reasons 
everything is misaligned and now i am stuck .
how i get the last 2 hour's files
if you are free then please message ...https://twitter.com/AnkitPa72761433

**Comment by SandeshGC** [comment]
Hey @Ankit-11525 , sorry I was busy today, did you find any solution for it?

**Comment by SandeshGC** [comment]
The site is working fine on my device, I think it has been fixed.

**Pull request merged**
