### PR TITLE
Added toggle button for changing theme.

### PR DESCRIPTION
**Pull request by Aarav238**
I have added toggle button inside navbar in all the webpages. After clicking on toggle button you can change theme to dark and vice-versa.
before clicking on toggle button
before

After clicking on toggle button
after

### CODE REVIEW

**Comment by Aarav238** [comment]
Please take a look on this and please add hacktoberfest label .

**Comment by Ankit-11525** [comment]
can you share the link of deployed version of it.
so that its easy for me to see changes

**Comment by Aarav238** [comment]
sure

**Comment by Aarav238** [comment]
I have done all the required changes.
Here is the link -> https://aarav238.github.io/Redstore/
please check it out @Ankit-11525

**Comment by Ankit-11525** [comment]
Please resolve it!
This branch has conflicts that must be resolved

**Comment by Aarav238** [comment]
done

**Comment by Aarav238** [comment]
thank you

**Pull request merged**
