### PR TITLE
add hover transition and animation effect in allProducts.html and index.html(latest products section and featured product section) 

### PR DESCRIPTION
**Pull request by Aarav238**
I have add transition and animation effect on hovering in **allproducts.html** (in **All Product** section) and in **index.html**(in **featured products** section and in **latest product** section). On hovering in product images transiton effect will be visible.Thank you @Ankit-11525 for assigning me this issue.I hope you will like it . Btw this is my first PR.

### CODE REVIEW

**Comment by Ankit-11525** [comment]
Please deploy at your end and share the link .or you can share the screenshot.
It also helps in future.
It will be very greatfull for me 😊

**Comment by Aarav238** [comment]
**Here is the link**  _->_
[ https://aarav238.github.io/RedStore/](url)

@Ankit-11525 Please check it out.
May be it take some seconds to load because of github server.

**Comment by Ankit-11525** [comment]
Link is not working and please resolve conflicts .

**Comment by Aarav238** [comment]
Can i Close this PR and raise another one i think some issue is there @Ankit-11525

**Comment by Aarav238** [comment]
I have resolve the conflicts.
here is the link ->
https://aarav238.github.io/RedStore/

Check by hovering on all the products in allproduct page(allproduct.html) and in homepage (index.html)
new

**Pull request merged**
