### PR TITLE
Added brand website links in the brands section

### PR DESCRIPTION
**Pull request by rtewari056**
### Type of change:
I have fixed the brands section on the website where I attached links with the logos. Now, when a user clicks on them it will redirect to the actual website of the brand.

Kindly review the code and your suggestions are welcome.

### CODE REVIEW

**Comment by Ankit-11525** [comment]
thanks that's great

**Comment by Ankit-11525** [comment]
Please deploy at your end so that i can see changes !
becoz at my end there are no changes in brand links may be its time taking process 
but please deploy at your end  which helps in future also.

**Comment by rtewari056** [comment]
> Please deploy at your end so that i can see changes and which may also helps in future also. becoz at my end may be its time taking process .

Alright

**Comment by rtewari056** [comment]
@Ankit-11525 Check out latest deployment here: https://rtewari056.github.io/e-commerce_redstore.github.io/

And kindly add labels in this pull request which is mentioned in the issue no. #15

**Comment by rtewari056** [comment]
@Ankit-11525 Please add hacktoberfest-accepted label

**Pull request merged**
