### PR TITLE
Dark Theme Added with a localstorage

### PR DESCRIPTION
**Pull request by helloArnab**
Dark theme is added with a local storage to keep the theme in storage.
Dark theme will make it more trendy and beautiful.
<br>

https://user-images.githubusercontent.com/99715406/195667692-962ad2b1-249b-4add-833b-29a4aea46310.mp4

### CODE REVIEW

**Comment by helloArnab** [comment]
Hope you like my work and accept my pr :)

**Comment by Ankit-11525** [comment]
Great work please resolve conflicts

**Comment by Ankit-11525** [comment]
Please deploy at your end! , it will also help in future and share the link

**Comment by helloArnab** [comment]
done

**Comment by helloArnab** [comment]
<a>https://helloarnab.github.io/e-commerce_redstore.github.io/</a>

**Comment by helloArnab** [comment]
your current dark theme is looking too bag and someone have changed the offer section alignment which i have fixed too :)
<br>
Screenshot (125)
Screenshot (124)

**Comment by Ankit-11525** [comment]
But it has some conflicts .

**Comment by Ankit-11525** [comment]
This branch has conflicts that must be resolved

**Comment by Ankit-11525** [comment]
But it is only for home page!

**Pull request closed without merging**
