### PR TITLE
mobile nav menu design improved

### PR DESCRIPTION
**Pull request by Dharmik3**
### before 
Screenshot 2022-10-08 at 1 23 47 PM

### after changes
Screenshot 2022-10-08 at 1 18 59 PM
hanges

### CODE REVIEW

**Comment by Ankit-11525** [comment]
Issue no ?

**Comment by Dharmik3** [comment]
I just directly made PR.Is it mandatory to raise an issue?

**Comment by Ankit-11525** [comment]
Just to close that issue

**Comment by Dharmik3** [comment]
If you assign this PR under hectober it would be helpful for me.
Thank you.

**Pull request merged**
