### PR TITLE
Dark theme is modified in all pages with a localstorage

### PR DESCRIPTION
**Pull request by helloArnab**
hope you remember me, I have closed that pr and adding a fresh pr.
I have added darkmode in all the pages.
<br>

https://user-images.githubusercontent.com/99715406/195996586-6a8db3f8-eae2-4659-8174-3d8739c2c880.mp4

<br>
<br>

Screenshot (127)
Screenshot (128)
Screenshot (129)
Screenshot (126)

### CODE REVIEW

**Comment by helloArnab** [comment]
https://helloarnab.github.io/e-commerce_redstore.github.io/

**Comment by helloArnab** [comment]
already fixed 3 conflict hope no more conflict occur ;)

**Comment by Ankit-11525** [comment]
I see the changes and i am happy with your hardwork, very satisfied dark color combination!

**Comment by helloArnab** [comment]
thanks it is really inspiring and it is my first open source contribution so i am happy to get such a complement

**Comment by Ankit-11525** [comment]
I want light theme as bydefault theme please raise new issue .
I'll merge it
And also some codes and files were lost :(
eg.. preloading page
@helloArnab

**Comment by helloArnab** [comment]
ok i am looking after the issue

**Comment by helloArnab** [comment]
can u do one thing revert the code and then i m creating a new pr

**Comment by helloArnab** [comment]
@Ankit-11525  please revert the code
i will create a new pr

**Comment by helloArnab** [comment]
and once done pls reply me

**Comment by Ankit-11525** [comment]
I have reverted this PR @helloArnab

**Comment by Ankit-11525** [comment]
You can review the current website

**Pull request merged**
