### PR TITLE
Updated copyright year to use js.

### LINKED ISSUE #4: Year in copyright of footer is wrong
I can update the footer to give the current year of the copyright

### PR DESCRIPTION
**Pull request by harikesh409**
Closes #4 

Screenshot:
image

### CODE REVIEW

**Comment by Ankit-11525** [comment]
Can you please share the updated footer screenshot ? so that i will review and merge it ..

**Comment by harikesh409** [comment]
@Ankit-11525 Added the footer screenshot.

**Comment by harikesh409** [comment]
Can you add the `hacktoberfest` topic to the repo.

**Comment by Ankit-11525** [comment]
Done!

**Pull request merged**
