### PR TITLE
Added a border effect to  Feature and  Latest product

### PR DESCRIPTION
**Pull request by theanimator20**
Hello, @Ankit-11525 

i have added a border effect (on hover)  to   **All the product cards** in order to improve the UI  and also to distinguish the products separately.Please Merge it or if any issues revert me the same.

Thank you
Screenshot 2022-10-11 121354

### CODE REVIEW

**Comment by theanimator20** [comment]
@Ankit-11525  If everything is Ok than Accept my merge request with the hacktoberfest label

**Comment by theanimator20** [comment]
U mean hosting the website?.

**Comment by Ankit-11525** [comment]
yaa you can easily deploy it in your github pages in 5 min

**Comment by theanimator20** [comment]
i have deploy the website please go through it 
https://product-border-effect.netlify.app/

**Comment by Ankit-11525** [comment]
It doesn't fit in our website or doesn't look good .
Please  work for another issue 
Hope you find more issues in our project
But i can't merge it , understand and All the Best

**Pull request closed without merging**
