### PR TITLE
Fixes #18 : Added toggle button to change theme

### LINKED ISSUE #18: Theme change needed
Theme change needed! with switching mode button

### PR DESCRIPTION
**Pull request by palashb01**
Light Mode:
ss3

Dark Mode:
ss4

### CODE REVIEW

**Comment by palashb01** [comment]
Hey @Ankit-11525, Please Review this, and add hacktoberfest-accepted label, Thanks.

**Comment by Ankit-11525** [comment]
Please resolve conflicts!!
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/Ankit-11525/e-commerce_redstore.github.io/pull/80/conflicts) or the  to resolve conflicts.
Conflicting files
index.html
style.css

**Comment by Aarav238** [comment]
i can make it more good by adding something more  . Please assign this issue to me.
@Ankit-11525

**Comment by Aarav238** [comment]
@palashb01  please resolve conflict

**Comment by palashb01** [comment]
@Ankit-11525 I have resolved the issue, Please Review it, Thanks.

**Comment by Ankit-11525** [comment]
Please use dark color as matched with theme do not use directly black

**Pull request closed without merging**
